version: '3.7'

networks:
  my-network:
    external: true

services:

  frontend:
    build: ./react_client
    links:
      - backend
    volumes:
      - './react_client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./flask_api
    ports:
      - "5000:5000"
    volumes:
      - "./flask_api:/flask_api/"